version: '3.8'

services:
  churn-prediction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberpunk-churn-dashboard
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./data:/app/data:ro
      - ./artifacts:/app/artifacts:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - churn-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: churn-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - churn-prediction
    restart: unless-stopped
    networks:
      - churn-network
    profiles:
      - production

networks:
  churn-network:
    driver: bridge
